# MarkdownDownInternal.
%prefix "mddi"

# Copied verbatim to the C header file before the generated parser implementation code.
%header {
#include "data.h"

#define PCC_AST_MANAGER_CUSTOM_DATA_DEFINED
typedef mdd_data_t pcc_ast_manager_custom_data_t;

#define PCC_AST_NODE_CUSTOM_DATA_DEFINED
typedef mdd_node_data_t pcc_ast_node_custom_data_t;
}

%import "code/pcc_ast.peg"

# Output data type as `$$`.
%value "pcc_ast_node_t *"
# User-defined data type passed to `pcc_create`.
%auxil "pcc_ast_manager_t *"

# Copied verbatim to the C source file before the generated parser implementation code.
%source {
#include <stdio.h>
#include <stdlib.h>

#include "utils.h"

// Get a character from the input.
#define PCC_GETCHAR(auxil) mdd_get_char_from_data(&auxil->custom)

static const char *dbg_str[] = { "Evaluating", "Matched", "Abandoned" };
#define PCC_DEBUG(auxil, event, rule, level, pos, buffer, length) \
    do {\
        if (event == 2) {\
            fprintf(stderr, "%*s%s %s\n", (int)((level) * 2), "", dbg_str[event], rule); \
        } else {\
            fprintf(stderr, "%*s%s %s @(%zu,%zu)\n", (int)((level) * 2), "", dbg_str[event], rule, pos, length); \
        }\
    } while (0)

int look_back_nonspace(mddi_context_t *ctx);

int inline_equation_pre(mddi_context_t *ctx);
int inline_equation_post(mddi_context_t *ctx);

}

######

document <- l:front_matter? r:block_list? end_of_file
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_DOCUMENT, $0s, $0e);
        mdd_node_append_child($$, l);
        mdd_node_append_child($$, r);
    }

front_matter <- '---' new_line front_matter_body? '---' new_line
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_FRONT_MATTER, $0s, $0e);
    }

front_matter_body <- ((!'---' !new_line .)* new_line)+

block_list <-
    l:block_list r:block
    {
        $$ = l;
        mdd_node_append_child($$, r);
        mdd_node_data_set_range(&$$->custom, $0s, $0e);
    }
    / e:block
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_BLOCK_LIST, $0s, $0e);
        mdd_node_append_child($$, e);
    }

block <-
    blank_line+
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_BLANK_LINE, $0s, $0e);
    }
    / (e:block_quote / e:verbatim / e:note / e:reference / e:plain)
    {
        $$ = e;
    }

# TODO: for block quote, we need to re-parse it separately after the main parse.
# For now, we will only parse the inline elements within it.
block_quote <-
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_BLOCK_QUOTE, $0s, $0e);
    }
    ('>' ' '? l:inline? new_line?
        {
            mdd_node_append_child($$, l);
        }
     (!'>' !blank_line r:inline new_line?
        {
            mdd_node_append_child($$, r);
        }
     )*
    )+
    {
        mdd_node_data_set_range(&$$->custom, $0s, $0e);
    }

verbatim <- nonblank_indented_line+
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_VERBATIM, $0s, $0e);
    }

reference <- nonindent_space !'[]' l:label ':' space_newline s:reference_source space_newline t:reference_title? blank_line+
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_REFERENCE, $0s, $0e);
        mdd_node_append_child($$, l);
        mdd_node_append_child($$, s);
        mdd_node_append_child($$, t);
        mdd_node_type_label_data_t *id = mdd_node_type_data_get_label(l);
        mdd_node_type_label_data_t *source = mdd_node_type_data_get_label(s);
        mdd_node_type_label_data_t *title = mdd_node_type_data_get_label(t);
        mdd_node_type_reference_data_new(&$$->custom,
            id ? &id->text : NULL,
            source ? &source->text : NULL,
            title ? &title->text : NULL);
        mdd_pointer_array_add(&auxil->custom.references, $$);
    }

reference_source <- nonspace_char+
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_LINK_SOURCE, $0s, $0e);
        mdd_node_type_label_data_new(&$$->custom, $0);
    }

reference_title <- (reference_title_single / reference_title_double / reference_title_parens)
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_LINK_TITLE, $0s, $0e);
        // Exclude the quotes.
        mdd_node_type_label_data_new1(&$$->custom, $0 + 1, strlen($0) - 2);
    }

reference_title_single <- '\'' (!('\'' space new_line / new_line) .)* '\''

reference_title_double <- '"' (!('"' space new_line / new_line) .)* '"'

reference_title_parens <- '(' (!(')' space new_line / new_line) .)* ')'

plain <- e:inlines end_line?
    {
        $$ = e;
        mdd_node_data_assign(&$$->custom, MDD_NODE_TYPE_PLAIN, $0s, $0e);
    }

inlines <-
    l:inlines r:inline_or_end_line
    {
        $$ = l;
        mdd_node_append_child($$, r);
        mdd_node_data_set_range(&$$->custom, $0s, $0e);
    }
    / e:inline_or_end_line
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_INLINES, $0s, $0e);
        mdd_node_append_child($$, e);
    }

inline_or_end_line <-
    !end_line e:inline
    {
        $$ = e;
    }
    / end_line &inline

inline <-
    (str
     / end_line
     / ul_or_star_line
     / spaces
     / e:strong
     / e:emph
     / e:strike
     / e:mark
     / e:image
     / e:link
     / e:note_reference
     / e:inline_note
     / e:code
     / e:inline_equation
     / e:mark_html
     / e:raw_html
     / e:entity
     / e:escaped_char
     / special_char
    )
    {
        $$ = e;
    }

mark <- '==' !whitespace
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_MARK, $0s, $0e);
    }
    (!'==' e:inline
        {
            mdd_node_append_child($$, e);
        }
    )+ &{ look_back_nonspace(ctx) } '=='
    {
        mdd_node_data_set_range(&$$->custom, $0s, $0e);
    }

mark_html <- mark_html_open
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_MARK, $0s, $0e);
    }
    (!mark_html_close (e:raw_html { mdd_node_append_child($$, e); } / .))* mark_html_close
    {
        mdd_node_data_set_range(&$$->custom, $0s, $0e);
    }

mark_html_open <- '<' space_newline ('mark' / 'MARK') space_newline html_attribute* '>'

mark_html_close <- '<' space_newline '/' ('mark' / 'MARK') space_newline '>'

inline_equation <- (inline_equation_single / inline_equation_multiple)
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_INLINE_EQUATION, $0s, $0e);
    }

inline_equation_single <- '$' &{ inline_equation_pre(ctx) } !'$' !'\\' nonspace_char '$' ![0-9]

inline_equation_multiple <- '$' &{ inline_equation_pre(ctx) } !'$' nonspace_char (!'$' !new_line .)+ '$' &{ inline_equation_post(ctx) } ![0-9]

ticks1 <- '`' !'`'
ticks2 <- '``' !'`'
ticks3 <- '```' !'`'
ticks4 <- '````' !'`'
ticks5 <- '`````' !'`'

code <- (ticks1 space ((!'`' nonspace_char)+ / !ticks1 '`'+ / !(space ticks1) (space_char / new_line !blank_line))+ space ticks1
    / ticks2 space ((!'`' nonspace_char)+ / !ticks2 '`'+ / !(space ticks2) (space_char / new_line !blank_line))+ space ticks2
    / !fenced_code_block_start_tick_line ticks3 space ((!'`' nonspace_char)+ / !ticks3 '`'+ / !(space ticks3) (space_char / new_line !blank_line))+ space ticks3
    / ticks4 space ((!'`' nonspace_char)+ / !ticks4 '`'+ / !(space ticks4) (space_char / new_line !blank_line))+ space ticks4
    / ticks5 space ((!'`' nonspace_char)+ / !ticks5 '`'+ / !(space ticks5) (space_char / new_line !blank_line))+ space ticks5)
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_CODE, $0s, $0e);
    }

fenced_code_block_start_tick <- '```' (!new_line !'`' .)*

fenced_code_block_start_tick_line <- fenced_code_block_start_tick new_line

inline_note <- '^['
    {
        // Need to fix the range at the end.
        $$ = mdd_node_create_v(MDD_NODE_TYPE_INLINE_NOTE, $0s, $0e);
    }
    (!']' e:inline
        {
            mdd_node_append_child($$, e);
        }
    )+
    ']'
    {
        mdd_node_data_set_range(&$$->custom, $0s, $0e);

        char_array_t note = mdd_char_array_new();
        mdd_char_array_assign1(&note, $0 + 2, strlen($0) - 3);
        mdd_node_type_note_data_new(&$$->custom, NULL, &note);
    }

note_reference <- note_reference_inner
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_NOTE_REFERENCE, $0s, $0e);
        char_array_t reference = mdd_char_array_new();
        mdd_char_array_assign1(&reference, $0 + 2, strlen($0) - 3);
        mdd_node_type_note_data_new(&$$->custom, &reference, NULL);
        mdd_pointer_array_add(&auxil->custom.note_references, $$);
    }

note_reference_inner <- '[^' (!new_line !']' .)+ ']'

note <- nonindent_space <note_reference_inner> ':' space <l:block blank_line* r:indented_block_list?>
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_NOTE, $0s, $0e);
        mdd_node_append_child($$, l);
        mdd_node_append_child($$, r);

        char_array_t reference = mdd_char_array_new();
        mdd_char_array_assign1(&reference, $1 + 2, strlen($1) - 3);
        char_array_t note = mdd_char_array_new();
        mdd_char_array_assign(&note, $2);
        mdd_node_type_note_data_new(&$$->custom, &reference, &note);

        mdd_pointer_array_add(&auxil->custom.notes, $$);
    }

indented_block_list <-
    l:indented_block_list &indent r:block blank_line*
    {
        $$ = l;
        mdd_node_append_child($$, r);
        mdd_node_data_set_range(&$$->custom, $0s, $0e);
    }
    / &indent e:block blank_line*
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_NOTE_BLOCK, $0s, $0e);
        mdd_node_append_child($$, e);
    }

link <- (e:explicit_link / e:reference_link / e:auto_link)
    {
        $$ = e;
    }

auto_link <-
    '<' ASCII_Letter+ '://' (!new_line !'>' .)+ '>'
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_AUTO_LINK_URL, $0s, $0e);

        char_array_t label = mdd_char_array_new();
        mdd_char_array_assign1(&label, $0 + 1, strlen($0) - 2);
        char_array_t source = mdd_char_array_duplicate(&label);

        mdd_node_type_link_data_new(&$$->custom, BOOL_FALSE,
            &label, &source, NULL, NULL, -1, -1);
    }
    / '<' 'mailto:'? [-A-Za-z0-9+_./!%~$]+ '@' (!new_line !'>' .)+ '>'
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_AUTO_LINK_EMAIL, $0s, $0e);

        char_array_t label = mdd_char_array_new();
        mdd_char_array_assign1(&label, $0 + 1, strlen($0) - 2);
        char_array_t source = mdd_char_array_duplicate(&label);

        mdd_node_type_link_data_new(&$$->custom, BOOL_FALSE,
            &label, &source, NULL, NULL, -1, -1);
    }

image <- '!' (e:explicit_link / e:explicit_link_size / e:reference_link)
    {
        assert(e);
        assert(e->type == PCC_AST_NODE_TYPE_VARIADIC);
        $$ = e;
        mdd_node_data_assign(&$$->custom, MDD_NODE_TYPE_IMAGE, $0s, $0e);
    }

reference_link <- (e:reference_link_double / e:reference_link_single)
    {
        $$ = e;
        mdd_pointer_array_add(&auxil->custom.reference_links, $$);
    }

reference_link_double <- l:label space_newline !'[]' r:label
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_LINK, $0s, $0e);
        mdd_node_append_child($$, l);
        if (r) {
            mdd_node_data_set_type(&r->custom, MDD_NODE_TYPE_LINK_REFERENCE);
        }
        mdd_node_append_child($$, r);
        mdd_node_type_label_data_t *label = mdd_node_type_data_get_label(l);
        mdd_node_type_label_data_t *reference = mdd_node_type_data_get_label(r);
        mdd_node_type_link_data_new(&$$->custom, BOOL_TRUE,
            label ? &label->text : NULL,
            NULL,
            NULL,
            reference ? &reference->text : NULL,
            -1, -1);
    }

reference_link_single <- e:label (space_newline '[]')?
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_LINK, $0s, $0e);
        // e is the label as well as the reference.
        mdd_node_append_child($$, e);
        mdd_node_type_label_data_t *label = mdd_node_type_data_get_label(e);
        char_array_t reference_text = mdd_char_array_new();
        if (label) {
            // Duplicate the text.
            reference_text = mdd_char_array_duplicate(&label->text);
        }
        mdd_node_type_link_data_new(&$$->custom, BOOL_TRUE,
            label ? &label->text : NULL,
            NULL,
            NULL,
            &reference_text,
            -1, -1);
        mdd_char_array_finalize(&reference_text);
    }

explicit_link_size <- l:label '(' space s:source space_newline t:title? space z:size space ')'
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_LINK, $0s, $0e);
        mdd_node_append_child($$, l);
        mdd_node_append_child($$, s);
        mdd_node_append_child($$, t);
        mdd_node_append_child($$, z);
        mdd_node_type_label_data_t *label = mdd_node_type_data_get_label(l);
        mdd_node_type_label_data_t *source = mdd_node_type_data_get_label(s);
        mdd_node_type_label_data_t *title = mdd_node_type_data_get_label(t);
        mdd_node_type_size_data_t *size = mdd_node_type_data_get_size(z);
        assert(size);
        mdd_node_type_link_data_new(&$$->custom, BOOL_FALSE,
            label ? &label->text : NULL,
            source ? &source->text : NULL,
            title ? &title->text : NULL,
            NULL,
            size->width, size->height);
    }

size <-
    '=' < [0-9]+ > 'x' < [0-9]+ >
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_LINK_SIZE, $0s, $0e);
        mdd_node_type_size_data_new(&$$->custom, atoi($1), atoi($2));
    }
    / '=' < [0-9]+ > 'x'
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_LINK_SIZE, $0s, $0e);
        mdd_node_type_size_data_new(&$$->custom, atoi($3), -1);
    }
    / '=x' < [0-9]+ >
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_LINK_SIZE, $0s, $0e);
        mdd_node_type_size_data_new(&$$->custom, -1, atoi($4));
    }

explicit_link <- l:label '(' space s:source space_newline t:title? space ')'
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_LINK, $0s, $0e);
        mdd_node_append_child($$, l);
        mdd_node_append_child($$, s);
        mdd_node_append_child($$, t);
        mdd_node_type_label_data_t *label = mdd_node_type_data_get_label(l);
        mdd_node_type_label_data_t *source = mdd_node_type_data_get_label(s);
        mdd_node_type_label_data_t *title = mdd_node_type_data_get_label(t);
        mdd_node_type_link_data_new(&$$->custom, BOOL_FALSE,
            label ? &label->text : NULL,
            source ? &source->text : NULL,
            title ? &title->text : NULL,
            NULL,
            -1, -1);
    }

source <-
    '<' < source_contents > '>'
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_LINK_SOURCE, $0s, $0e);
        mdd_node_type_label_data_new(&$$->custom, $1);
    }
    / source_contents
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_LINK_SOURCE, $0s, $0e);
        mdd_node_type_label_data_new(&$$->custom, $0);
    }

source_contents <- ((!'(' !')' !'>' nonspace_char)+ / '(' source_contents ')')*

title <- (title_single / title_double)
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_LINK_TITLE, $0s, $0e);
        // Exclude the quotes.
        mdd_node_type_label_data_new1(&$$->custom, $0 + 1, strlen($0) - 2);
    }

title_single <- '\'' (!('\'' / new_line) .)* '\''

title_double <- '"' (!('"' / new_line) .)* '"'

label <- '[' e:label_inner? ']'
    {
        if (e) {
            $$ = e;
            mdd_node_data_set_range(&$$->custom, $0s, $0e);
            mdd_node_type_label_data_new1(&$$->custom, $0 + 1, strlen($0) - 2);
        } else {
            $$ = mdd_node_create_0(MDD_NODE_TYPE_LINK_LABEL, $0s, $0e);
            mdd_node_type_label_data_new(&$$->custom, "");
        }
    }

label_inner <-
    # [^abc] is for note reference.
    l:label_inner (!'^' !']' !'[' r:label_inline)
    {
        $$ = l;
        mdd_node_append_child($$, r);
        mdd_node_data_set_range(&$$->custom, $0s, $0e);
    }
    / (!'^' !']' !'[' e:label_inline)
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_LINK_LABEL, $0s, $0e);
        mdd_node_append_child($$, e);
    }

label_inline <-
    (str
    / end_line
    / space
    / e:raw_html
    / e:entity
    / escaped_char
    / special_char)
    {
        $$ = e;
    }

escaped_char <- '\\' !new_line ([-\\`~|*_{}[\]()#+.!><] / special_char_ext)

hex_entity <- '&' '#' [Xx] [0-9a-fA-F]+ ';'
dec_entity <- '&' '#' [0-9]+ ';'
char_entity <- '&' [A-Za-z0-9]+ ';'

entity <- (hex_entity / dec_entity / char_entity)
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_ENTITY, $0s, $0e);
    }

raw_html <- (html_comment / html_block_script / html_tag)
    {
        $$ = mdd_node_create_0(MDD_NODE_TYPE_HTML, $0s, $0e);
    }

html_comment <- '<!--' (!'-->' .)* '-->'

html_tag <- '<' space_newline '/'? alphanumeric_ascii+ space_newline html_attribute* '/'? space_newline '>'

strike <- '~~' !whitespace
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_STRIKE, $0s, $0e);
    }
    (!'~~' e:inline
        {
            mdd_node_append_child($$, e);
        }
    )+ &{ look_back_nonspace(ctx) } '~~'
    {
        mdd_node_data_set_range(&$$->custom, $0s, $0e);
    }

strong <- (e:strong_star / e:strong_ul)
    {
        $$ = e;
    }

strong_star <- '**' !whitespace
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_STRONG, $0s, $0e);
    }
    (!'**' e:inline
        {
            mdd_node_append_child($$, e);
        }
    )+ &{ look_back_nonspace(ctx) } '**'
    {
        mdd_node_data_set_range(&$$->custom, $0s, $0e);
    }

strong_ul <- '__' !whitespace
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_STRONG, $0s, $0e);
    }
    (!'__' e:inline
        {
            mdd_node_append_child($$, e);
        }
    )+ &{ look_back_nonspace(ctx) } '__'
    {
        mdd_node_data_set_range(&$$->custom, $0s, $0e);
    }

emph <- (e:emph_star / e:emph_ul)
    {
        $$ = e;
    }

emph_star <- '*' !whitespace
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_EMPH, $0s, $0e);
    }
    ((!'*' e:inline / e:strong_star)
        {
            mdd_node_append_child($$, e);
        }
    )+ &{ look_back_nonspace(ctx) } '*'
    {
        mdd_node_data_set_range(&$$->custom, $0s, $0e);
    }

emph_ul <- '_' !whitespace
    {
        $$ = mdd_node_create_v(MDD_NODE_TYPE_EMPH, $0s, $0e);
    }
    ((!'_' e:inline / e:strong_star)
        {
            mdd_node_append_child($$, e);
        }
    )+ &{ look_back_nonspace(ctx) } '_'
    {
        mdd_node_data_set_range(&$$->custom, $0s, $0e);
    }

ul_or_star_line <- ul_line / star_line

ul_line <- '____' '_'* / space_char '_'+ &space_char

star_line <- '****' '*'* / space_char '*'+ &space_char

str <- normal_char (normal_char / '_'+ &alphanumeric)*

normal_char <- !(special_char / space_char / new_line ) .

special_char <- '~' / '*' / '_' / '`' / '&' / '[' / ']' / '(' / ')' / '<' / '!' / '#' / '\\' / '\'' / '"' / special_char_ext

special_char_ext <- '^' / '$' / '|' / '='

alphanumeric <- ASCII_C_alnum / Unicode_Letter / Unicode_Number

alphanumeric_ascii <- ASCII_C_alnum

space_char <- ' ' / '\t'

nonspace_char <- !space_char !new_line .

space <- space_char*

space_newline <- space (new_line space)?

spaces <- space_char+

blank_line <- space new_line

line <-
    (!'\r' !'\n' .)* new_line
    / .+ end_of_file

indent <- '\t' / '    '

nonindent_space <- '   ' / '  ' / ' ' / ''

indented_line <- indent line

nonblank_indented_line <- !blank_line indented_line

end_line <- line_break / terminal_end_line / normal_end_line

line_break <- '  ' normal_end_line

normal_end_line <- space new_line !blank_line !'>'
    !(line ('='+ / '-'+) new_line)

terminal_end_line <- space new_line end_of_file

whitespace <- space_char / new_line

new_line <- '\r\n' / '\n' / '\r'

end_of_file <- !.

quoted <- '"' (!'"' .)* '"' / '\'' (!'\'' .)* '\''

html_attribute <- (alphanumeric_ascii / '-')+ space_newline ('=' space_newline (quoted / (!'>' nonspace_char)+))? space_newline

# Block-Level HTML content.
html_block_script_open <- '<' space_newline ('script' / 'SCRIPT') space_newline html_attribute* '>'
html_block_script_close <- '<' space_newline '/' ('script' / 'SCRIPT') space_newline '>'
html_block_script <- html_block_script_open (!html_block_script_close .)* html_block_script_close

######

%import "char/ascii_character_group.peg"
%import "unicode_general_category_fix.peg"

# End of the rules. All codes below will be copied to the C source file.
%%

void pcc_ast_manager_custom_data__initialize(pcc_ast_manager_custom_data_t *obj) {
    mdd_data_initialize(obj);
}

void pcc_ast_manager_custom_data__finalize(pcc_ast_manager_custom_data_t *obj) {
    mdd_data_finalize(obj);
}

void pcc_ast_node_custom_data__initialize(pcc_ast_node_custom_data_t *obj) {
    mdd_node_data_initialize(obj);
}

void pcc_ast_node_custom_data__finalize(pcc_ast_node_custom_data_t *obj) {
    mdd_node_data_finalize(obj);
}

int look_back_nonspace(mddi_context_t *ctx) {
    const char *buf = ctx->buffer.buf + ctx->cur;
    if (ctx->cur == 0) {
        return 1;
    }
    const unsigned char ch = *(buf - 1);
    if (ch != ' ' && ch != '\t' && ch != '\n' && ch != '\r') {
        return 1;
    }
    return 0;
}

int inline_equation_pre(mddi_context_t *ctx) {
    const char *buf = ctx->buffer.buf + ctx->cur;
    assert(ctx->cur > 0);
    assert(*(buf - 1) == '$');
    if (ctx->cur < 2) {
        return 1;
    }
    const unsigned char ch = *(buf - 2);
    if (ch != '$' && (ch < '0' || ch > '9') && ch != '\\') {
        return 1;
    }
    return 0;
}

int inline_equation_post(mddi_context_t *ctx) {
    const char *buf = ctx->buffer.buf + ctx->cur;
    assert(ctx->cur >= 2);
    const unsigned char ch = *(buf - 2);
    if (ch != ' ' && ch != '\t' && ch != '\\') {
        return 1;
    }
    return 0;
}
